### ISSUE TITLE
Remove alpaka/test/acc/TestAccs.hpp

### ISSUE THREAD

**Issue by SimeonEhrig** [ComputationalRadiationPhysics/vikunja#14]
Instead of `alpaka/test/acc/TestAccs.hpp` use `alpaka/example/ExampleDefaultAcc.hpp`. `TestAccs.hpp` is just for internal usage and not provided by a alpaka installation.

**Comment by sliwowitz** [comment]
`alpaka/example/ExampleDefaultAcc.hpp` is not present in alpaka 0.5.0 release, we might want to just copy it to vikunja if we want to support 0.5.0.

**Comment by sbastrakov** [comment]
Maybe it is more practical to wait a little bit until 0.6.0 release and then at some point switch to it in vikunja, and only then to make this change to `ExampleDefaultAcc`?

**Comment by SimeonEhrig** [comment]
> `alpaka/example/ExampleDefaultAcc.hpp` is not present in alpaka 0.5.0 release, we might want to just copy it to vikunja if we want to support 0.5.0.

I missed this, because with the latest supported dev version the problem is solved. I think your suggestion is the easiest way. We add the header, release a alpaka 0.5.0 compatible version and remove it afterwards, if we go to alpaka 0.6.0

**Comment by SimeonEhrig** [comment]
Solved in #21
